jobs:
- job: test_suite
  displayName: Test suite
  pool:
    name: Hosted macOS
  steps:

  - template: scripts/ci/common-setup.yml

  - script: yarn run test
    displayName: Run test suite
    env:
      TEST_JUNIT_XML_PATH: $(Pipeline.Workspace)/test-results.xml

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: $(Pipeline.Workspace)/test-results.xml
      testRunTitle: Mocha test suite
    condition: succeededOrFailed()