# Run on a schedule
trigger: none
pr: none
name: Release

jobs:
- job: release
  displayName: Release
  pool:
    name: Hosted macOS
  steps:

  - template: scripts/ci/common-setup.yml

#   - script: yarn run test
#     displayName: Run test suite
#     env:
#       TEST_JUNIT_XML_PATH: $(Agent.HomeDirectory)/test-results.xml

  - script: yarn global add vsce
    displayName: Install vsce

#   - script: >
#       node ./scripts/prepare-nightly-build.js
#       -v "$VERSION" -i "$NAME" -n "$DISPLAYNAME" -d "$DESCRIPTION" -p "$PUBLISHER"
#     displayName: Generate package.json
#     env:
#       NAME: monday-vscode-extension-insiders
#       DISPLAYNAME: Monday VSCode Extension Nightly Build
#       DESCRIPTION: Nightly Build Monday VSCode Extension
#       PUBLISHER: Netzer

  - script: yarn release
    displayName: Create version

  - script: vsce publish -p "$TOKEN" --yarn --noVerify
    displayName: Publish
    env:
      TOKEN: $(vsce.token)